[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nexuseval"
version = "0.1.0"
description = "An open-source LLM evaluation framework."
authors = [{name = "Shubham Salokhe", email = "shubhamsalokhe@ymail.com"}]
readme = "README.md"
license = {text = "MIT"}
dependencies = [
    "openai>=1.0.0",
    "tqdm"
]